export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';


export const REQUEST__STARTED = 'REQUEST__STARTED';
export const REQUEST__FAILED = 'REQUEST__FAILED';
export const REQUEST__FINISHED = 'REQUEST__FINISHED';


export const LOGIN__REQUESTED = 'login-requested';
export const LOGIN__SUCCEEDED = 'login-succeeded';
export const LOGIN__FAILED = 'login-failed';
export const LOGIN__COMPLETED = 'login-completed';

export const LOGOUT__REQUESTED = 'logout-requested';
export const LOGOUT__COMPLETED = 'logout-completed';


export const CHANGE_PASSWORD__REQUESTED = 'CHANGE_PASSWORD__REQUESTED';
export const CHANGE_PASSWORD__SUCCEEDED = 'CHANGE_PASSWORD__SUCCEEDED';
export const CHANGE_PASSWORD__FAILED = 'CHANGE_PASSWORD__FAILED';


export const PROFILE__REQUESTED = 'PROFILE__REQUESTED';
export const PROFILE__REQUESTED__SUCCEEDED = 'PROFILE__REQUESTED__SUCCEEDED';
export const PROFILE__REQUESTED__FAILED = 'PROFILE__REQUESTED__FAILED';



export const REGISTER__REQUESTED = 'REGISTER__REQUESTED';
export const REGISTER__REQUEST__SUCCEEDED = 'REGISTER__REQUEST__SUCCEEDED';
export const REGISTER__REQUEST__FAILED = 'REGISTER__REQUEST__FAILED';
